### ISSUE TITLE
UUIDというものを理解して、使用してみましょう。

### ISSUE THREAD

**Issue by satoren** [ringokuroshiro/my-todo-list#3]
https://github.com/ringokuroshiro/my-todo-list/blob/ff7a184fb0d4f7c4a95ef73511014fdf957d0c25/src/App.tsx#L19

**Comment by ringokuroshiro** [comment]
UUID（Universally Unique Identifier）とは、ソフトウェア上でオブジェクトを一意に識別するための識別子である。

UUIDを作るのは大変そう。
https://qiita.com/psn/items/d7ac5bdb5b5633bae165

react uuidでググってみる。
https://www.npmjs.com/package/uuid
を見つける。

インストールして使ってみたものをpushしました。
https://github.com/ringokuroshiro/my-todo-list/commit/09b7d25b5c4f62475aaab7164fbc5d93288c37c3

**Comment by satoren** [comment]
uuid作るタイミングが不適切です。
必要になったタイミングで作りましょう

**Comment by ringokuroshiro** [comment]
uuidを作るタイミングをaddToDoする時に変更しました。
